# Ford.com Digital Analytics

## Phase 1 - Exploratory Data Analysis

**Goal&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:** Understand web session behavior and identify patterns that predict conversion. \
**Dataset&nbsp;:** Google Analytics Sample Dataset (Google Merchandise store) 

**Author&nbsp;:** Mayuri Kawale \
**Date&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:** February 27, 2026

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print('Environment ready!')
print(f'Pandas version: {pd.__version__}')

Environment ready!
Pandas version: 3.0.1

## Task 2 - Load & Look the Dataset

In [2]:
df = pd.read_csv('../data/train.csv')
print(f'Shape: {df.shape}')

Shape: (903653, 12)

In [3]:
# look first few rows:
df.head()

,channelGrouping,date,device,fullVisitorId,geoNetwork,sessionId,socialEngagementType,totals,trafficSource,visitId,visitNumber,visitStartTime
0,Organic Search,20160902,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",1.131660e+18,"{""continent"": ""Asia"", ""subContinent"": ""Western...",1131660440785968503_1472830385,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""1"", ""pageviews"": ""1"",...","{""campaign"": ""(not set)"", ""source"": ""google"", ...",1472830385,1,1472830385
1,Organic Search,20160902,"{""browser"": ""Firefox"", ""browserVersion"": ""not ...",3.773060e+17,"{""continent"": ""Oceania"", ""subContinent"": ""Aust...",377306020877927890_1472880147,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""1"", ""pageviews"": ""1"",...","{""campaign"": ""(not set)"", ""source"": ""google"", ...",1472880147,1,1472880147
2,Organic Search,20160902,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",3.895550e+18,"{""continent"": ""Europe"", ""subContinent"": ""South...",3895546263509774583_1472865386,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""1"", ""pageviews"": ""1"",...","{""campaign"": ""(not set)"", ""source"": ""google"", ...",1472865386,1,1472865386
3,Organic Search,20160902,"{""browser"": ""UC Browser"", ""browserVersion"": ""n...",4.763450e+18,"{""continent"": ""Asia"", ""subContinent"": ""Southea...",4763447161404445595_1472881213,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""1"", ""pageviews"": ""1"",...","{""campaign"": ""(not set)"", ""source"": ""google"", ...",1472881213,1,1472881213
4,Organic Search,20160902,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",2.729440e+16,"{""continent"": ""Europe"", ""subContinent"": ""North...",27294437909732085_1472822600,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""1"", ""pageviews"": ""1"",...","{""campaign"": ""(not set)"", ""source"": ""google"", ...",1472822600,2,1472822600

In [4]:
# look for column names, data types and any missing values:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 903653 entries, 0 to 903652
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   channelGrouping       903653 non-null  str
 1   date                  903653 non-null  int64
 2   device                903653 non-null  str
 3   fullVisitorId         903653 non-null  float64
 4   geoNetwork            903653 non-null  str
 5   sessionId             903653 non-null  str
 6   socialEngagementType  903653 non-null  str
 7   totals                903653 non-null  str
 8   trafficSource         903653 non-null  str
 9   visitId               903653 non-null  int64
 10  visitNumber           903653 non-null  int64
 11  visitStartTime        903653 non-null  int64
dtypes: float64(1), int64(4), str(7)
memory usage: 82.7 MB

In [5]:
# basic statistics for numerical columns:
df.describe()

,date,fullVisitorId,visitId,visitNumber,visitStartTime
count,9.036530e+05,9.036530e+05,9.036530e+05,903653.000000,9.036530e+05
mean,2.016589e+07,4.505845e+18,1.485007e+09,2.264897,1.485007e+09
std,4.697698e+03,3.071128e+18,9.022124e+06,9.283735,9.022124e+06
min,2.016080e+07,4.823600e+12,1.470035e+09,1.000000,1.470035e+09
25%,2.016103e+07,1.593050e+18,1.477561e+09,1.000000,1.477561e+09
50%,2.017011e+07,4.388190e+18,1.483949e+09,1.000000,1.483949e+09
75%,2.017042e+07,7.194900e+18,1.492759e+09,1.000000,1.492759e+09
max,2.017080e+07,5.198310e+19,1.501657e+09,395.000000,1.501657e+09

##### Notice: This statistical summary is not particularly useful for the above numerical columns like date, IDs, etc. But in general they serve a good starting point for summarizing the nature of numerical features.

In [6]:
# check if there are any empty strings or json strings
df.head().T

,0,1,2,3,4
channelGrouping,Organic Search,Organic Search,Organic Search,Organic Search,Organic Search
date,20160902,20160902,20160902,20160902,20160902
device,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...","{""browser"": ""Firefox"", ""browserVersion"": ""not ...","{""browser"": ""Chrome"", ""browserVersion"": ""not a...","{""browser"": ""UC Browser"", ""browserVersion"": ""n...","{""browser"": ""Chrome"", ""browserVersion"": ""not a..."
fullVisitorId,1131660000000000000.0,377306000000000000.0,3895550000000000000.0,4763450000000000000.0,27294400000000000.0
geoNetwork,"{""continent"": ""Asia"", ""subContinent"": ""Western...","{""continent"": ""Oceania"", ""subContinent"": ""Aust...","{""continent"": ""Europe"", ""subContinent"": ""South...","{""continent"": ""Asia"", ""subContinent"": ""Southea...","{""continent"": ""Europe"", ""subContinent"": ""North..."
sessionId,1131660440785968503_1472830385,377306020877927890_1472880147,3895546263509774583_1472865386,4763447161404445595_1472881213,27294437909732085_1472822600
socialEngagementType,Not Socially Engaged,Not Socially Engaged,Not Socially Engaged,Not Socially Engaged,Not Socially Engaged
totals,"{""visits"": ""1"", ""hits"": ""1"", ""pageviews"": ""1"",...","{""visits"": ""1"", ""hits"": ""1"", ""pageviews"": ""1"",...","{""visits"": ""1"", ""hits"": ""1"", ""pageviews"": ""1"",...","{""visits"": ""1"", ""hits"": ""1"", ""pageviews"": ""1"",...","{""visits"": ""1"", ""hits"": ""1"", ""pageviews"": ""1"",..."
trafficSource,"{""campaign"": ""(not set)"", ""source"": ""google"", ...","{""campaign"": ""(not set)"", ""source"": ""google"", ...","{""campaign"": ""(not set)"", ""source"": ""google"", ...","{""campaign"": ""(not set)"", ""source"": ""google"", ...","{""campaign"": ""(not set)"", ""source"": ""google"", ..."
visitId,1472830385,1472880147,1472865386,1472881213,1472822600
visitNumber,1,1,1,1,2
visitStartTime,1472830385,1472880147,1472865386,1472881213,1472822600

## Task 3 - Data Cleaning
### Step 1 - Unpack JSON Columns

In [7]:
import json

json_cols = ["device", "geoNetwork", "totals", "trafficSource"]

for col in json_cols:
    df[col] = df[col].apply(json.loads) # converts json string to a python dictionary
    normalized = pd.json_normalize(df[col])  # expands the dictionary into separate columns of a new dataframe
    normalized.columns = [f'{col}_{c}' for c in normalized.columns] # rename the columns with original column info
    df = df.drop(col, axis=1).join(normalized) # drops json columns and adds new separate columns

print(f'New shape: {df.shape}')
df.head()

New shape: (903653, 55)

,channelGrouping,date,fullVisitorId,sessionId,socialEngagementType,visitId,visitNumber,visitStartTime,device_browser,device_browserVersion,...,trafficSource_adwordsClickInfo.criteriaParameters,trafficSource_isTrueDirect,trafficSource_referralPath,trafficSource_adwordsClickInfo.page,trafficSource_adwordsClickInfo.slot,trafficSource_adwordsClickInfo.gclId,trafficSource_adwordsClickInfo.adNetworkType,trafficSource_adwordsClickInfo.isVideoAd,trafficSource_adContent,trafficSource_campaignCode
0,Organic Search,20160902,1.131660e+18,1131660440785968503_1472830385,Not Socially Engaged,1472830385,1,1472830385,Chrome,not available in demo dataset,...,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Organic Search,20160902,3.773060e+17,377306020877927890_1472880147,Not Socially Engaged,1472880147,1,1472880147,Firefox,not available in demo dataset,...,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Organic Search,20160902,3.895550e+18,3895546263509774583_1472865386,Not Socially Engaged,1472865386,1,1472865386,Chrome,not available in demo dataset,...,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Organic Search,20160902,4.763450e+18,4763447161404445595_1472881213,Not Socially Engaged,1472881213,1,1472881213,UC Browser,not available in demo dataset,...,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Organic Search,20160902,2.729440e+16,27294437909732085_1472822600,Not Socially Engaged,1472822600,2,1472822600,Chrome,not available in demo dataset,...,not available in demo dataset,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# look for column names, data types and any missing values:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 903653 entries, 0 to 903652
Data columns (total 55 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   channelGrouping                                    903653 non-null  str
 1   date                                               903653 non-null  int64
 2   fullVisitorId                                      903653 non-null  float64
 3   sessionId                                          903653 non-null  str
 4   socialEngagementType                               903653 non-null  str
 5   visitId                                            903653 non-null  int64
 6   visitNumber                                        903653 non-null  int64
 7   visitStartTime                                     903653 non-null  int64
 8   device_browser                                     903653 non-null  str
 9   device_browserVersion                              903653 non-null  str
 10  device_browserSize                                 903653 non-null  str
 11  device_operatingSystem                             903653 non-null  str
 12  device_operatingSystemVersion                      903653 non-null  str
 13  device_isMobile                                    903653 non-null  bool
 14  device_mobileDeviceBranding                        903653 non-null  str
 15  device_mobileDeviceModel                           903653 non-null  str
 16  device_mobileInputSelector                         903653 non-null  str
 17  device_mobileDeviceInfo                            903653 non-null  str
 18  device_mobileDeviceMarketingName                   903653 non-null  str
 19  device_flashVersion                                903653 non-null  str
 20  device_language                                    903653 non-null  str
 21  device_screenColors                                903653 non-null  str
 22  device_screenResolution                            903653 non-null  str
 23  device_deviceCategory                              903653 non-null  str
 24  geoNetwork_continent                               903653 non-null  str
 25  geoNetwork_subContinent                            903653 non-null  str
 26  geoNetwork_country                                 903653 non-null  str
 27  geoNetwork_region                                  903653 non-null  str
 28  geoNetwork_metro                                   903653 non-null  str
 29  geoNetwork_city                                    903653 non-null  str
 30  geoNetwork_cityId                                  903653 non-null  str
 31  geoNetwork_networkDomain                           903653 non-null  str
 32  geoNetwork_latitude                                903653 non-null  str
 33  geoNetwork_longitude                               903653 non-null  str
 34  geoNetwork_networkLocation                         903653 non-null  str
 35  totals_visits                                      903653 non-null  str
 36  totals_hits                                        903653 non-null  str
 37  totals_pageviews                                   903553 non-null  str
 38  totals_bounces                                     450630 non-null  str
 39  totals_newVisits                                   703060 non-null  str
 40  totals_transactionRevenue                          11515 non-null   str
 41  trafficSource_campaign                             903653 non-null  str
 42  trafficSource_source                               903653 non-null  str
 43  trafficSource_medium                               903653 non-null  str
 44  trafficSource_keyword                              400724 non-null  str
 45  trafficSource_adwordsClickInfo.criteriaParameters  903653 non-null  str
 46  trafficSource_isTrueDirect                         274005 non-null  object
 47  trafficSource_referralPath                         330941 non-null  str
 48  trafficSource_adwordsClickInfo.page                21460 non-null   str
 49  trafficSource_adwordsClickInfo.slot                21460 non-null   str
 50  trafficSource_adwordsClickInfo.gclId               21561 non-null   str
 51  trafficSource_adwordsClickInfo.adNetworkType       21460 non-null   str
 52  trafficSource_adwordsClickInfo.isVideoAd           21460 non-null   object
 53  trafficSource_adContent                            10946 non-null   str
 54  trafficSource_campaignCode                         1 non-null       str
dtypes: bool(1), float64(1), int64(4), object(2), str(47)
memory usage: 373.2+ MB

### Step 2 - Check for missing values

In [9]:
missing = df.isnull().sum() # looks for missing values and sums along the column
missing[missing>0] # all columns with missing values

totals_pageviews                                   100
totals_bounces                                  453023
totals_newVisits                                200593
totals_transactionRevenue                       892138
trafficSource_keyword                           502929
trafficSource_isTrueDirect                      629648
trafficSource_referralPath                      572712
trafficSource_adwordsClickInfo.page             882193
trafficSource_adwordsClickInfo.slot             882193
trafficSource_adwordsClickInfo.gclId            882092
trafficSource_adwordsClickInfo.adNetworkType    882193
trafficSource_adwordsClickInfo.isVideoAd        882193
trafficSource_adContent                         892707
trafficSource_campaignCode                      903652
dtype: int64

### Step 3 - Fill the missing values

##### `totals_transactionRevenue` is the most important feature. It helps to determine the conversion rate. The missing value implies the number of visits that did not generate any revenue. So, these missing values can be easily replaced by `0`  
##### *bounce* means the visitor left after viewing only one page. The visitor did not bounce imply they visited multiple pages. Missing value implies `0` bounces. Replace missing value in `totals_bounces` with `0`.  
##### `totals_newVisits` refer to number of new vistor that is visiting for the first time. Missing value implies they are not returning visitors. So, replace the missing value with `0`.
##### `trafficSource_keyword` refers to visits using specific keyword via a search engine. Missing value here or other `trafficSource` variables indicate another method was used. So, replace the missing values with `NA` or `not applicable`.
##### `totals_pageviews` has only 100 missing values out of 900K+ values. These can be safely replaced with `0`.

In [10]:
# fill missing value with appropriate values
df['totals_transactionRevenue'] = df['totals_transactionRevenue'].fillna(0) # replace with 0
df['totals_bounces'] = df['totals_bounces'].fillna(0) # replace with 0
df['totals_newVisits'] = df['totals_newVisits'].fillna(0) # replace with 0
df['totals_pageviews'] = df['totals_pageviews'].fillna(0) # replace with 0

sources = ['keyword', 'isTrueDirect', 'referralPath', 'adwordsClickInfo.page', 'adwordsClickInfo.slot', 
           'adwordsClickInfo.gclId', 'adwordsClickInfo.adNetworkType', 'adwordsClickInfo.isVideoAd', 'adContent', 
           'campaignCode']

for source in sources:
    df[f'trafficSource_{source}'] = df[f'trafficSource_{source}'].fillna("not applicable") # replace with 'not applicable'

### Check there are no more missing values

In [11]:
#check for missing values
missing = df.isnull().sum()
missing[missing > 0]

Series([], dtype: int64)

### Checking the data types

In [12]:
# check datatypes of the new dataframe
df.dtypes

channelGrouping                                          str
date                                                   int64
fullVisitorId                                        float64
sessionId                                                str
socialEngagementType                                     str
visitId                                                int64
visitNumber                                            int64
visitStartTime                                         int64
device_browser                                           str
device_browserVersion                                    str
device_browserSize                                       str
device_operatingSystem                                   str
device_operatingSystemVersion                            str
device_isMobile                                         bool
device_mobileDeviceBranding                              str
device_mobileDeviceModel                                 str
device_mobileInputSelector                               str
device_mobileDeviceInfo                                  str
device_mobileDeviceMarketingName                         str
device_flashVersion                                      str
device_language                                          str
device_screenColors                                      str
device_screenResolution                                  str
device_deviceCategory                                    str
geoNetwork_continent                                     str
geoNetwork_subContinent                                  str
geoNetwork_country                                       str
geoNetwork_region                                        str
geoNetwork_metro                                         str
geoNetwork_city                                          str
geoNetwork_cityId                                        str
geoNetwork_networkDomain                                 str
geoNetwork_latitude                                      str
geoNetwork_longitude                                     str
geoNetwork_networkLocation                               str
totals_visits                                            str
totals_hits                                              str
totals_pageviews                                      object
totals_bounces                                        object
totals_newVisits                                      object
totals_transactionRevenue                             object
trafficSource_campaign                                   str
trafficSource_source                                     str
trafficSource_medium                                     str
trafficSource_keyword                                    str
trafficSource_adwordsClickInfo.criteriaParameters        str
trafficSource_isTrueDirect                            object
trafficSource_referralPath                               str
trafficSource_adwordsClickInfo.page                      str
trafficSource_adwordsClickInfo.slot                      str
trafficSource_adwordsClickInfo.gclId                     str
trafficSource_adwordsClickInfo.adNetworkType             str
trafficSource_adwordsClickInfo.isVideoAd              object
trafficSource_adContent                                  str
trafficSource_campaignCode                               str
dtype: object

#### Note: The data types are wrong for various features/variables. 

Convert to datetime format  
`data`  
`visitStartTime`


Convert to string format  
`fullVisitorId`  
`visitId`

Convert to integer format  
`totals_visits`
`totals_hits`
`totals_pageviews`
`totals_bounces`
`totals_newVisits` 
`totals_transactionRevenue`

Ideally, convert to boolean format, however the missing values are replaced with strings. Keep it as is for now, and encode it as categorical variable during feature engineering  
`trafficSource_isTrueDirect`
`trafficSource_adwordsClickInfo.isVideoAd`

In [13]:
#convert the data type
df['date'] = pd.to_datetime(df['date'], format = '%Y%m%d') # date format
df['visitStartTime'] = pd.to_datetime(df['visitStartTime'], unit = 's') # time stamp in seconds
df['visitId'] = df['visitId'].astype(str) # convert to string

df['fullVisitorId'] = df['fullVisitorId'].astype(str) # convert to string

#convert totals columns to int
cols = ['visits', 'hits', 'pageviews', 'bounces', 'newVisits']
for col in cols:
    df[f'totals_{col}'] = df[f'totals_{col}'].astype(int)

df['totals_transactionRevenue'] = df['totals_transactionRevenue'].astype(float) #convert to float

In [14]:
#verify the fixes
df[['date', 'visitStartTime', 'visitId', 'fullVisitorId', 
    'totals_visits', 'totals_hits', 'totals_pageviews', 
    'totals_bounces', 'totals_newVisits', 'totals_transactionRevenue']].dtypes

date                         datetime64[us]
visitStartTime                datetime64[s]
visitId                                 str
fullVisitorId                           str
totals_visits                         int64
totals_hits                           int64
totals_pageviews                      int64
totals_bounces                        int64
totals_newVisits                      int64
totals_transactionRevenue           float64
dtype: object